description: segment masks on imagenet1k
target:
 service: sing
 name: GenAI-Shared-CanadaCtr
 workspace_name: turing-norwayeast-ws
environment:
 image: pytorch/pytorch:1.9.0-cuda10.2-cudnn7-devel
code:
 local_dir: ./
storage:
 v_haochen2:
  storage_account_name: ussclowpriv100data
  container_name: v-haochen2
  is_output: True
 data:
  storage_account_name: ussclowpriv100data
  container_name: jindwang
  mount_dir: /mnt/data
jobs:
- name: segm_imagenet
  sku: xxx
  command:
   - git clone git@github.com:qiuk2/MaskImageNet.git
   - cd MaskImageNet
   - azcopy cp "https://msramcg.blob.core.windows.net/xiaohao/CropFormer_hornet_3x_03823a.pth?sv=2021-10-04&st=2023-06-10T06%3A49%3A04Z&se=2025-10-11T06%3A49%3A00Z&sr=c&sp=rawdlf&sig=VZxZab4LWI6xjQoQD52VGKA6encMLmAOHrvnOuWgwL8%3D" ./
#   - azcopy cp "https://msramcg.blob.core.windows.net/xiaohao/ImageNet2012/?sv=2021-10-04&st=2023-06-10T06%3A49%3A04Z&se=2025-10-11T06%3A49%3A00Z&sr=c&sp=rawdlf&sig=VZxZab4LWI6xjQoQD52VGKA6encMLmAOHrvnOuWgwL8%3D" ./ --recursive
#   - mv ImageNet2012 data
   - bash run.sh 0-3 4