description: training jobs for vpa on imagenet1k
target:
 service: sing
 name: GenAI-Shared-CanadaCtr
 workspace_name: turing-norwayeast-ws
environment:
 image: pytorch/pytorch:2.2.2-cuda12.1-cudnn8-devel
 setup:
  - python -m pip install -U pip
  - pip install accelerate
  - pip install einops tqdm 
  - pip install ruamel.yaml==0.17.40
  - pip install wandb
  - pip install flash-attn
  - pip install transformers datasets
  - pip install -U xformers
  - pwd
  - sh scripts/azcopy_in1k.sh
  - sh scripts/download_vae.sh
  - pip install ruamel-yaml
code:
 local_dir: ./
storage:
 v_haochen2:
  storage_account_name: ussclowpriv100data
  container_name: v-haochen2
  is_output: True
 data:
  storage_account_name: ussclowpriv100data
  container_name: jindwang
  mount_dir: /mnt/data
jobs:
- name: train_vqvae_z8v4096_var16_lr2e-4_ep200_bs512_in1k
  sku: 80G8-H100-IB-NvLink
  command:
  - /home/aiscuser/.local/bin/accelerate launch --multi_gpu --mixed_precision=bf16 --num_processes=8 train.py --config configs/vqvae_z8v4096_var16.yaml --learning_rate 2e-4 --output_dir /mnt/v_haochen2/projects/vpa_nips2024/train_experiments --num_epochs 200