# data

#dataset_name: coco
#data:
#  annotation_path: /home/mcg/annotations/instances_train2017.json
#  img_dir: /home/mcg/train2017
#  image_size: 256

dataset_name: imagenetM
data_dir: /mnt/data/ImageNet2012
image_size: 256
batch_size: 16
num_workers: 4
# training
num_epochs: 30
optimizer: adamw
learning_rate: 1e-4
weight_decay: 0.05
lr_scheduler: lin0
lr_warmup_steps: 0.01
log_interval: 500
save_interval: epoch
mixed_precision: bf16
# vq model
v_patch_nums: [1, 2, 3, 4, 5, 6, 8, 10, 13, 16]
v_patch_layers: [1, 2, 3, 4, 5, 6, 8, 10, 13, 16]
depth: 16
embed_dim: 1024
drop_path_rate: 0.1
# condiiton model
condition_model: class_embedder
num_classes: 1000
cond_drop_rate: 0.1
multi_cond: True