apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: mpi
spec:
  slotsPerWorker: 8
  runPolicy:
    cleanPodPolicy: Running
    backoffLimit: 0
  mpiReplicaSpecs:
    Launcher:
      restartPolicy: Never
      replicas: 1
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: xl6
          nodeSelector:
            brightcomputing.com/node-category: 'gaudi'
          volumes:
          - name: home
            persistentVolumeClaim:
              claimName: xl6-home-pvc
          - name: scratch
            emptyDir: {}
          - name: ceph
            hostPath:
              path: /voyager/ceph/users/xl6
              type: Directory
          hostIPC: true
          containers:
          - name: gaudi-container
            image: vault.habana.ai/gaudi-docker/1.13.0/ubuntu22.04/habanalabs/pytorch-installer-2.1.0:latest
            imagePullPolicy: Always
            resources:
              requests:
                cpu: 2
                memory: 4Gi
              limits:
                cpu: 4
                memory: 8Gi
            volumeMounts:
            - name: home
              mountPath: /home/xl6
            - name: scratch
              mountPath: /scratch
            - name: ceph
              mountPath: /ceph
            workingDir: /home/xl6/VPA
            command: ["/bin/bash", "-c"]
            args:
            - >-
                printenv ;
                touch /ceph/test.txt ;
                sleep 15s;
                export HOSTSFILE=${HOSTSFILE:-$OMPI_MCA_orte_default_hostfile};
                declare -xr MASTER_ADDR=$(head -n 1 $HOSTSFILE | sed -n s/[[:space:]]slots.*//p);
                declare -xr MASTER_PORT=${MASTER_PORT:-15566};
                export HOME=/ceph/local_packages;
                export PATH=$HOME/.local/bin:$PATH;
                export PYTHONPATH=$PYTHONPATH:/ceph/local_packages/.local/lib/python3.10/site-packages;
                chmod 777 /home/xl6/VPA;
                mpirun -x MASTER_ADDR -x MASTER_PORT -x PYTHONPATH -n 96 --allow-run-as-root --npernode 8 --bind-to core --map-by ppr:4:socket:PE=6 --report-bindings --tag-output --merge-stderr-to-stdout -x PT_HPU_LAZY_MODE=1 python3 train_mask_var_hpu_mpi.py  --batch_size 1 --dataset_name imagenetC --data_dir /ceph/ImageNet2012 --gpus 8 --output_dir ImageNetC_lr8e-5_d24_multi_cond_0508 --multi_cond True --config configs/train_mask_var_ImageNetC_d24.yaml --var_pretrained_path pretrained/var_d24.pth
    Worker:
      replicas: 12
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: xl6
          volumes:
          - name: home
            persistentVolumeClaim:
              claimName: xl6-home-pvc
          - name: scratch
            emptyDir: {}
          - name: ceph
            hostPath:
              path: /voyager/ceph/users/xl6
              type: Directory
          hostIPC: true
          containers:
          - name: gaudi-container
            image: vault.habana.ai/gaudi-docker/1.13.0/ubuntu22.04/habanalabs/pytorch-installer-2.1.0:latest
            imagePullPolicy: Always
            resources:
              requests:
                cpu: 95
                memory: 409Gi
                habana.ai/gaudi: 8
                hugepages-2Mi: 95000Mi
              limits:
                cpu: 95
                memory: 409Gi
                habana.ai/gaudi: 8
                hugepages-2Mi: 95000Mi
            volumeMounts:
            - name: home
              mountPath: /home/xl6
            - name: scratch
              mountPath: /scratch
            - name: ceph
              mountPath: /ceph
            workingDir: /home/xl6/VPA